#!/usr/bin/env python3
"""Idempotently add strict freehold filtering and price-drop feature cards."""
from pathlib import Path

PATH = Path(__file__).resolve().parent / "dashboard" / "index.html"
s = PATH.read_text(encoding="utf-8")

if "drops-card" not in s:
    market_note = ".market-note{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:8px;font-size:12px;color:var(--muted)}"
    drops_css = ".drops-card{margin-top:16px;padding:16px;border-color:#fed7aa;background:linear-gradient(135deg,#fff 0%,#fffaf5 100%)}.drops-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.drops-title{margin:0;font-size:18px}.drops-count{display:inline-flex;align-items:center;padding:5px 9px;border-radius:999px;background:#fff7ed;color:#c2410c;border:1px solid #fed7aa;font-size:12px;font-weight:800}.drops-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:12px}.drop-card{position:relative;border:1px solid #fed7aa;border-radius:14px;background:#fff;padding:13px;cursor:pointer;min-width:0}.drop-card:hover{box-shadow:0 8px 24px rgba(194,65,12,.08);transform:translateY(-1px)}.drop-rank{position:absolute;top:10px;right:10px;color:#c2410c;font-size:11px;font-weight:900}.drop-title{font-size:13px;font-weight:800;padding-right:30px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.drop-address{font-size:11px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:3px}.drop-prices{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:11px}.drop-old{color:#94a3b8;text-decoration:line-through;font-size:12px}.drop-arrow{color:#fb923c;font-weight:900}.drop-new{font-size:16px;font-weight:900}.drop-change{margin-top:7px;color:#c2410c;font-size:13px;font-weight:900}.drop-meta{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:10px}.drops-empty{grid-column:1/-1;padding:20px 0 4px;text-align:center;color:#94a3b8;font-size:13px}"
    s = s.replace(market_note, market_note + drops_css, 1)
    s = s.replace("@media(max-width:1100px){.metrics{", "@media(max-width:1100px){.drops-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.metrics{", 1)
    s = s.replace(".market-card{padding:12px;margin-top:10px}.market-head{display:block}", ".drops-card{padding:12px;margin-top:10px}.drops-head{align-items:center}.drops-grid{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;gap:9px;padding-bottom:3px}.drop-card{flex:0 0 min(82vw,320px);scroll-snap-align:start}.market-card{padding:12px;margin-top:10px}.market-head{display:block}", 1)

    metrics = '<section class="metrics"><div class="metric"><div class="metric-label">表示中</div><div id="metricShown" class="metric-value">—</div></div><div class="metric"><div class="metric-label">掲載レコード</div><div id="metricTotal" class="metric-value">—</div></div><div class="metric"><div class="metric-label">価格取得率</div><div id="metricCoverage" class="metric-value">—</div></div><div class="metric"><div class="metric-label">価格変更</div><div id="metricChanged" class="metric-value">—</div></div></section>'
    panel = metrics + '<section class="card drops-card" aria-label="値下げ物件"><div class="drops-head"><div><h2 class="drops-title">値下げされた物件</h2><div class="muted" style="font-size:12px;margin-top:3px">初回観測価格から下落した掲載を、下落率・下落額の大きい順に表示</div></div><span id="dropsCount" class="drops-count">—</span></div><div id="dropsGrid" class="drops-grid"><div class="drops-empty">価格履歴を確認中…</div></div></section>'
    s = s.replace(metrics, panel, 1)

    normalize = "function normalize(r){return{...r,id:r.listing_id||r.id,propertyId:r.property_id||r.listing_id||r.id,source:String(r.source||''),priceYen:r.price_yen==null?null:Number(r.price_yen),land:r.land_area_sqm??r.land_sqm??null,building:r.building_area_sqm??r.building_sqm??null,built:r.built_year_month??r.built??null,station:r.access??r.station??null,days:Number(r.observed_days??r.listing_days??0),firstSeen:r.first_seen??null,history:Array.isArray(r.price_history)?r.price_history:[]}}"
    functions = normalize + "\nfunction priceHistory(x){let m=new Map();for(let p of x.history||[]){if(Array.isArray(p)&&p[0]&&p[1]!=null)m.set(String(p[0]),Number(p[1]));else if(p&&p.date&&(p.price_yen??p.price)!=null)m.set(String(p.date),Number(p.price_yen??p.price))}return[...m.entries()].filter(([,v])=>Number.isFinite(v)&&v>0).sort((a,b)=>a[0].localeCompare(b[0]))}\nfunction priceDrop(x){let h=priceHistory(x),current=x.priceYen;if(h.length){let first=h[0][1],latest=current??h.at(-1)[1],amount=first-latest;if(amount>0)return{first,current:latest,amount,pct:amount/first*100,date:h.at(-1)[0]}}let raw=Number(x.price_change_yen||0);if(raw<0&&current!=null){let first=current-raw,amount=-raw;return{first,current,amount,pct:amount/first*100,date:dateOnly(x.last_seen)}}return null}\nfunction renderPriceDrops(){let drops=items.map(x=>({x,d:priceDrop(x)})).filter(v=>v.d).sort((a,b)=>b.d.pct-a.d.pct||b.d.amount-a.d.amount);$('dropsCount').textContent=drops.length.toLocaleString('ja-JP')+'件';let top=drops.slice(0,12);$('dropsGrid').innerHTML=top.length?top.map(({x,d},i)=>`<article class=\"drop-card\" data-drop-id=\"${esc(x.id)}\" tabindex=\"0\"><span class=\"drop-rank\">#${i+1}</span><div class=\"drop-title\">${esc(x.title||x.address||x.id)}</div><div class=\"drop-address\">${esc(x.address||'')}</div><div class=\"drop-prices\"><span class=\"drop-old\">${yen(d.first)}</span><span class=\"drop-arrow\">→</span><span class=\"drop-new\">${yen(d.current)}</span></div><div class=\"drop-change\">▼ ${yen(d.amount)}（${d.pct.toFixed(1)}%）</div><div class=\"drop-meta\"><span class=\"${sourceClass(x.source)}\">${esc(sourceLabel(x.source))}</span>${linkHtml(x,'物件を見る')}</div></article>`).join(''):`<div class=\"drops-empty\">観測開始後、値下げが確認された物件はまだありません。</div>`;document.querySelectorAll('[data-drop-id]').forEach(el=>el.onclick=e=>{if(e.target.closest('a'))return;show(el.dataset.dropId)})}"
    s = s.replace(normalize, functions, 1)
    s = s.replace("$('status').textContent=`${a.length.toLocaleString()}件表示 / ${items.length.toLocaleString()}件取得済み。表示時スクレイピングなし。`;drawMarketChart(a)}", "$('status').textContent=`${a.length.toLocaleString()}件表示 / ${items.length.toLocaleString()}件取得済み。所有権の土地・土地建物のみ。表示時スクレイピングなし。`;renderPriceDrops();drawMarketChart(a)}", 1)

if "NON_FREEHOLD_RE" not in s:
    marker = "function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[m]))}"
    freehold_js = marker + "const NON_FREEHOLD_RE=/(?:借地権|定期借地|普通借地|旧法借地|新法借地|地上権|賃借権|借地期間|借地料|地代)/;function isNonFreehold(x){let explicit=[x.land_right_status,x.land_rights,x.land_right,x.land_ownership,x.ownership,x.tenure,x.rights,x.property_rights,x['土地権利'],x['権利形態']].filter(Boolean).join(' '),fallback=[x.title,x.address,x.description,x.remarks,x.notes].filter(Boolean).join(' ');return String(x.land_right_status||'').toLowerCase()==='leasehold'||NON_FREEHOLD_RE.test(explicit+' '+fallback)}"
    s = s.replace(marker, freehold_js, 1)
    s = s.replace("String(x.title||'')!=='資料請求');populateSources();", "String(x.title||'')!=='資料請求'&&!isNonFreehold(x));populateSources();", 1)

s = s.replace("品川区・目黒区 / 夜間バッチ収集 / 価格履歴を永続保存", "品川区・目黒区 / 所有権の土地・土地建物のみ / 夜間バッチ収集")
PATH.write_text(s, encoding="utf-8")
print(f"patched {PATH}")
